import type { Feature } from './features.ts';

/**
 * End-to-end scenarios over the example projects in examples/. Each runs in isolation: its own workspaces root, its
 * own database, a fresh copy of its example project and of the harness definitions. A `real` scenario starts real
 * Claude Code runs and is skipped once the account's 5-hour or weekly limit is used up, to be continued once it resets.
 */
export interface Scenario {
  id: string;
  title: string;
  projects: ('todo-cli' | 'bookshelf-api' | 'handbook')[];
  real: boolean;
  /** Runs talk to a scripted model: real Claude Code and harness, with the model's moves set by the scenario */
  scripted?: boolean;
  covers: Feature[];
  steps: string[];
}

export const SCENARIOS: Scenario[] = [
  {
    id: 'onboard',
    title: 'Onboard a code-only project',
    projects: ['todo-cli'],
    real: true,
    covers: [
      'project.discover', 'project.enable', 'definition.materialize', 'trigger.defaults', 'trigger.unverified-ignored',
      'automation.graph-build', 'orchestrator.feed-room', 'feed.size', 'feed.approve', 'state.verification',
      'kb.index', 'kb.types', 'kb.validate', 'run.checkout', 'run.usage-share', 'run.process-limits', 'automation.summarization',
    ],
    steps: [
      'Project listed disabled; enabling it materializes the definitions and proposes the default triggers',
      'No trigger starts anything while unverified',
      'Graph build runs until the feed is full, pauses, and continues as items are approved',
      'Build reports coverage each run and ends complete; every written entity is valid and typed',
      'Each run records its usage share and leaves no checkout behind',
    ],
  },
  {
    id: 'goal-to-landed-work',
    title: 'From a goal to validated work on the main line',
    projects: ['bookshelf-api'],
    real: true,
    covers: [
      'trigger.schedule', 'trigger.event', 'automation.exploration', 'automation.preparation', 'automation.summarization',
      'automation.implementation', 'automation.validation', 'state.entity-ahead', 'guard.land', 'orchestrator.serial-automations',
      'kb.mcp', 'kb.search',
    ],
    steps: [
      'Exploration reads the goals and writes research plus an action entity that advances a goal',
      'Approving the action makes it entity_ahead; preparation writes a plan, summarization makes it a Harness/Plan',
      'Approving the plan starts implementation; its work lands on the main line in one commit',
      'implementation_finished starts validation; the seeded failing test ends fixed on the main line or raised as an issue',
      'Automation runs never overlap within the project',
    ],
  },
  {
    id: 'exploration-idle',
    title: 'Exploration stays idle when every goal is met',
    projects: ['todo-cli'],
    real: true,
    covers: ['automation.exploration'],
    steps: ['With every goal marked met, a scheduled exploration run writes nothing'],
  },
  {
    id: 'consistency',
    title: 'Inconsistencies raised, resolved and dismissed',
    projects: ['handbook'],
    real: true,
    covers: [
      'automation.consistency-check', 'feed.issue-options', 'feed.wont-resolve', 'feed.contradictions', 'automation.chat',
      'feed.diff',
    ],
    steps: [
      'Consistency check files the seeded contradiction and naming clash as issues with options; changes no entity',
      'The contradicted entity counts the open contradiction',
      'Picking an option starts a chat run that fixes the entity; the card shows a diff until approved',
      "Won't resolve closes the other issue with the reason",
    ],
  },
  {
    id: 'retention',
    title: 'Spent entities retired',
    projects: ['handbook'],
    real: true,
    covers: ['automation.retention', 'feed.approve'],
    steps: [
      'Retention proposes one plan retiring the old unreferenced DevTask and research; keeps the referenced decision and goals',
      'Approving the plan removes them from the main line',
    ],
  },
  {
    id: 'chat-and-send-back',
    title: 'Chat, send back and a requested plan',
    projects: ['bookshelf-api'],
    real: true,
    covers: ['automation.chat', 'feed.send-back', 'run.messages', 'run.context', 'run.kill', 'automation.summarization'],
    steps: [
      'A chat answers a question from the knowledge base with the card parts added as context',
      'A follow-up message continues the same run; the transcript is summarized into a chat entity',
      'Send back with a comment changes the entity in a chat run; the changed entity waits in the feed again',
      'A chat asked for a plan writes plans/<name>.md, summarized into a Harness/Plan',
      'A killed chat ends killed; what it wrote so far reaches the feed',
    ],
  },
  {
    id: 'artifact-change',
    title: 'A user edit to an artifact resummarized',
    projects: ['handbook'],
    real: true,
    covers: ['guard.main-line-index', 'state.artifact-ahead', 'state.updating', 'automation.summarization', 'settings.persist'],
    steps: [
      'A user commit on the main line changes a summarized document and one in an excluded path',
      'Its entity goes artifact_ahead, then updating, and one summarization run rewrites the card; synced after',
      'The excluded document is never summarized',
    ],
  },
  {
    id: 'interview',
    title: 'Interview by voice',
    projects: ['bookshelf-api'],
    real: true,
    covers: ['automation.interview', 'voice.routing', 'voice.stream'],
    steps: [
      '"Interview <topic>" spoken with the chat screen open starts an interview run',
      'Answers, a skip and a question back each land in one document under interviews/',
      '"Stop interview" ends it; the document is summarized into entities once',
    ],
  },
  {
    id: 'optimization',
    title: 'Optimization proposes from recurring issues',
    projects: ['bookshelf-api'],
    real: true,
    covers: ['automation.optimization', 'metrics.agent', 'definition.approve', 'definition.variant'],
    steps: [
      'After chats in a project repeat the same correction, optimization in the harness workspace records the counts and proposes a definition change with evidence',
      'Approving it materializes it into every enabled project; a definition variant is recorded on the runs it shapes',
    ],
  },
  {
    id: 'guard-in-a-run',
    title: 'The guard holds a real run to valid entities',
    projects: ['todo-cli'],
    real: true,
    covers: ['guard.live-check', 'guard.stop-blocked', 'guard.inconsistent-issue', 'guard.land'],
    steps: [
      'A chat told to write an over-limit card with a broken reference is flagged at once',
      'The run cannot stop until it fixes the entity, then lands with its own message',
      'A run killed while its entity is invalid lands it with an issue raised over it',
    ],
  },
  {
    id: 'models-by-risk',
    title: 'Models chosen by risk',
    projects: ['bookshelf-api'],
    real: true,
    covers: ['run.models', 'settings.persist'],
    steps: ['In risk mode, a low-risk and a high-risk implementation start on the models the settings map them to'],
  },
  {
    id: 'scheduling',
    title: 'Scheduling across three projects',
    projects: ['todo-cli', 'bookshelf-api', 'handbook'],
    real: false,
    covers: [
      'orchestrator.feed-room', 'orchestrator.serial-automations', 'orchestrator.parallel-user-runs',
      'orchestrator.concurrent-total', 'trigger.schedule', 'trigger.on-demand', 'feed.rank', 'feed.size',
    ],
    steps: [
      'Due loops queue only while the feed has room, across all three projects',
      'One automation run per project at a time; user runs start at once; the total is never passed',
      'The feed ranks across projects and holds at most the feed size',
    ],
  },
  {
    id: 'lifecycle',
    title: 'Disable, restart and reset',
    projects: ['todo-cli'],
    real: false,
    covers: [
      'project.disable', 'project.reset', 'project.harness-protected', 'orchestrator.restart-recovery', 'legacy.run-branches',
      'guard.conflict',
    ],
    steps: [
      'Disabling stops the build; enabling resumes it',
      'A run lost at restart is queued again, and failed past the limit',
      'Leftover momentum/ branches land oldest first and go',
      'A run whose entity changed on the main line meanwhile lands on the run side and raises the conflict',
      'Reset leaves no entity, checkout or index row and builds afresh; the harness workspace refuses',
    ],
  },
  {
    id: 'feed-and-patterns',
    title: 'Reactions become patterns and metrics',
    projects: ['handbook'],
    real: false,
    covers: [
      'feed.patterns', 'metrics.attention', 'metrics.understanding', 'metrics.implementation', 'metrics.per-automation',
      'feed.approve', 'feed.send-back',
    ],
    steps: [
      'Ten approvals of one type become an automatic approval pattern',
      'Every metric of the metrics page has a value after the reactions and runs',
    ],
  },
  {
    id: 'access',
    title: 'API, MCP and app',
    projects: ['bookshelf-api'],
    real: false,
    covers: ['api.auth', 'api.http', 'api.mcp', 'voice.auth', 'app.pages', 'app.timeline', 'settings.persist', 'kb.search', 'kb.types'],
    steps: [
      'Wrong password refused; every HTTP route answers to its contract with a session and refuses without',
      'Every momentum MCP tool works against the project',
      'Voice sockets refuse an app that is not signed in',
      'Every app page loads and approves, sends back and chats against the backend',
      'The timeline lists the sign-ins, settings, reactions, chats and one event per run newest first, and shows the next one live beside the app',
    ],
  },
  {
    id: 'conversations',
    title: 'A day of chatting with the knowledge base',
    projects: ['bookshelf-api'],
    real: false,
    scripted: true,
    covers: [
      'automation.chat', 'run.messages', 'run.context', 'automation.summarization', 'feed.diff', 'feed.approve', 'app.pages', 'run.failure',
      'state.summarized-once', 'feed.once',
    ],
    steps: [
      'A question asked in the Chat tab is answered in the conversation, with the card parts added as context reaching the agent',
      'A follow-up continues the same chat; its transcript is summarized into a chat entity the chat list links to',
      'A chat asked to change an entity lands it unverified; the card shows a diff against the verified version until approved',
      'A chat the API fails for ends failed with the reason; the next message resumes it and gets an answer',
      'Approving or sending back one item from two devices at once acts once',
    ],
  },
  {
    id: 'feature-delivery',
    title: 'A feature from a goal to fixed, validated code',
    projects: ['bookshelf-api'],
    real: false,
    scripted: true,
    covers: [
      'automation.exploration', 'automation.preparation', 'automation.implementation', 'automation.validation', 'automation.summarization',
      'automation.chat', 'trigger.schedule', 'trigger.event', 'trigger.unverified-ignored', 'state.entity-ahead', 'guard.land',
      'feed.issue-options', 'orchestrator.serial-automations', 'metrics.implementation', 'run.checkout',
    ],
    steps: [
      'Exploration on its schedule proposes research and a feature that advances a goal',
      'An approved feature waits as entity_ahead while implementation is not approved; preparation writes a plan, summarized into a Harness/Plan',
      'Approving the plan starts implementation: code, tests and the updated card land in one commit; approving the result brings the plan in sync',
      'The finished implementation starts validation, which raises a defect; the user resolves it in their own words and the fix lands',
      'Automation runs of the project never overlapped and left no checkout behind',
    ],
  },
  {
    id: 'maintenance',
    title: 'Keeping a handbook consistent and lean',
    projects: ['handbook'],
    real: false,
    scripted: true,
    covers: [
      'automation.consistency-check', 'automation.retention', 'feed.issue-options', 'feed.wont-resolve', 'feed.contradictions',
      'metrics.agent', 'metrics.understanding', 'guard.main-line-index', 'settings.persist', 'kb.validate', 'feed.retire',
    ],
    steps: [
      'The nightly consistency check files a contradiction and a naming clash as issues with options and records its counts; nothing else changes',
      'Picking the recommended option fixes the guide and its document in a chat; the issue retires and the contradiction count drops',
      "Won't resolve keeps the clash verified with the reason; it is no longer counted as open",
      'With the lifetimes the user set, retention proposes retiring spent entities; approving retires them but keeps one a new decision still relies on',
      'A user deleting an entity by hand on the main line is indexed at once: it leaves the index and the broken reference lowers consistency',
    ],
  },
  {
    id: 'graph-build-cycle',
    title: 'Building a knowledge graph through pauses, stops and failures',
    projects: ['todo-cli'],
    real: false,
    scripted: true,
    covers: [
      'project.enable', 'automation.graph-build', 'automation.summarization', 'orchestrator.feed-room', 'feed.size', 'feed.approve',
      'project.disable', 'app.timeline', 'metrics.per-automation', 'run.failure',
    ],
    steps: [
      'Enabling the project starts the build; its first run is told the room in the feed and its documents are summarized',
      'With the feed full the build waits; approving makes room and the next run continues from the reported progress',
      'Stopping the build in Settings ends the run in progress; resuming starts the next one',
      'A build whose runs keep failing stops after three failures in a row and says why, instead of retrying forever',
      'Resumed, the build completes: coverage 1, an estimate from the runs, and nothing more queued',
    ],
  },
  {
    id: 'interruptions',
    title: 'Runs interrupted by restarts, the guard and the user',
    projects: ['todo-cli'],
    real: false,
    scripted: true,
    covers: [
      'orchestrator.restart-recovery', 'run.kill', 'run.messages', 'guard.live-check', 'guard.stop-blocked', 'guard.inconsistent-issue',
      'guard.land', 'kb.validate', 'automation.consistency-check',
    ],
    steps: [
      'The harness restarting mid-run queues the automation run again; it resumes its session and lands its work once',
      'A chat lost at restart fails, yet what it wrote lands; the next message resumes it',
      'A run writing an invalid entity is told at once, cannot stop until it fixes it, then lands valid under its own message',
      'A run that never fixes its entity lands it after two tries with an issue raised over it',
      'Stopping a chat from its conversation lands what it wrote so far, and the timeline says the user stopped it',
    ],
  },
  {
    id: 'harness-tuning',
    title: 'Tuning the harness: models, definitions and triggers',
    projects: ['bookshelf-api'],
    real: false,
    scripted: true,
    covers: [
      'run.models', 'settings.persist', 'automation.optimization', 'metrics.agent', 'definition.approve', 'definition.materialize',
      'definition.variant', 'definition.review', 'trigger.on-demand', 'trigger.schedule',
    ],
    steps: [
      'Per automation, each run starts on the model the settings give its automation',
      "By risk, the estimator applies the user's rules: a typo fix starts on haiku, a schema change on opus",
      'Chats repeating one correction lead optimization in the harness to count it and propose a definition change',
      'Approving the proposal materializes it into the project and its variant is recorded on the runs it shapes; an agent file changed without approval is never materialized',
      'Triggers the user edits by hand take effect: without on_demand it refuses starts, and a new schedule is followed',
    ],
  },
  {
    id: 'devices',
    title: 'A phone and a laptop, signed in, offline and back',
    projects: ['handbook'],
    real: false,
    scripted: true,
    covers: ['api.auth', 'voice.auth', 'api.mcp', 'feed.approve', 'feed.send-back', 'app.pages', 'app.timeline', 'app.offline', 'feed.once', 'settings.persist'],
    steps: [
      'Two devices sign in side by side; a wrong password is refused and recorded on the timeline',
      'Signing out on one device ends only its session: its API, MCP and voice requests are refused',
      'Swipes made while the back-end is unreachable wait on the phone and land once it is back; one the laptop also made counts once',
      'A project logo is served with the project and recorded; removing it falls back to the drawn one; a file that is not an image is refused',
      'The timeline filters by project and actor and pages back without gaps or repeats',
    ],
  },
  {
    id: 'project-churn',
    title: 'Projects cloned, switched off and removed while the harness runs',
    projects: ['handbook'],
    real: false,
    scripted: true,
    covers: ['project.discover', 'project.churn', 'project.enable', 'project.disable', 'trigger.defaults', 'orchestrator.serial-automations', 'feed.rank', 'run.checkout'],
    steps: [
      'A repository cloned under the root while the harness runs is listed, disabled, without a restart',
      'Enabled, a project whose main line is master gets its triggers there and its runs land on master',
      'Disabling a project keeps its queued runs from starting and its items out of the feed; enabling it again starts them',
      'A project folder removed from the root leaves the list and the feed, and the harness goes on',
    ],
  },
  {
    id: 'documents',
    title: 'Documents edited by hand and by runs, kept summarized',
    projects: ['handbook'],
    real: false,
    scripted: true,
    covers: [
      'guard.main-line-index', 'state.artifact-ahead', 'state.updating', 'state.summarized-once', 'automation.summarization', 'settings.persist',
      'orchestrator.serial-automations', 'run.failure',
    ],
    steps: [
      'One commit editing two documents starts one summarization run that rewrites both cards',
      'A summarization that finds a card still right leaves it synced, not stuck updating',
      'A failed summarization leaves its entities behind their documents until the next edit summarizes them',
      'Two quick edits of one document: the second is summarized after the first, and the card ends on the latest',
      'A run editing an excluded document and a summarized one hands only the summarized one to summarization',
    ],
  },
  {
    id: 'voice',
    title: 'Talking to the harness on every screen',
    projects: ['bookshelf-api'],
    real: false,
    scripted: true,
    covers: ['voice.routing', 'voice.stream', 'automation.interview', 'automation.chat', 'run.context', 'automation.summarization'],
    steps: [
      'Said on the explorer, a phrase becomes the search; on an entity, a question asks about it and a command changes it',
      'Said on a new chat, a question starts a chat and what is said next goes on in it; "stop interview" there is ignored',
      'An interview started by voice asks one question at a time and writes every answer, skip and question back into one document',
      '"Stop interview" ends it and its document is summarized into an entity once',
      'After a restart nothing said before is acted on again',
    ],
  },
  {
    id: 'todo-cli-release',
    title: 'todo-cli from a weekend script to its 1.1 release',
    projects: ['todo-cli'],
    real: false,
    scripted: true,
    covers: [
      'state.new-files', 'state.artifact-ahead', 'state.summarized-once', 'automation.summarization', 'automation.chat', 'automation.implementation',
      'feed.send-back', 'feed.diff', 'state.entity-ahead', 'guard.main-line-index',
    ],
    steps: [
      'A module the developer commits by hand is summarized into a new card, since no entity covered it',
      'A feature request from the chat becomes a user story; implemented, its result is sent back for a test and approved with it',
      'A version bump is summarized into the repository card; a README tweak that changes nothing the card says leaves the feed as it was',
      'The release: a chat writes the changelog and a release note that references what shipped',
      'A small fix by the developer re-summarizes the one card over that file',
    ],
  },
  {
    id: 'bug-lifecycle',
    title: 'A bookshelf bug from the report to the fix, and a regression',
    projects: ['bookshelf-api'],
    real: false,
    scripted: true,
    covers: [
      'automation.chat', 'automation.implementation', 'automation.validation', 'trigger.event', 'trigger.schedule', 'metrics.implementation',
      'feed.retire', 'feed.issue-options', 'orchestrator.parallel-user-runs', 'trigger.on-demand',
    ],
    steps: [
      'A bug a reader reports through the chat is filed and counted open',
      'Approved, the bug is fixed and validated; it counts as fixed once the fix is approved',
      'A duplicate report is sent back and retired',
      "The nightly validation catches a developer's regression; picking the fix option repairs it",
      'A hotfix started on demand runs at once beside the automation run in progress',
    ],
  },
  {
    id: 'refactoring',
    title: 'Refactoring bookshelf: files renamed, split, deleted and reverted',
    projects: ['bookshelf-api'],
    real: false,
    scripted: true,
    covers: ['state.moved-files', 'state.new-files', 'state.artifact-ahead', 'automation.summarization', 'feed.retire', 'metrics.understanding'],
    steps: [
      'A renamed module: the card over it follows the new path',
      'Routes split out of the server into a new file: one summarization run puts both on the API card',
      'A deleted design document: its entity is retired once nothing references it',
      'The rename reverted: the card follows the file back and the graph stays consistent',
    ],
  },
  {
    id: 'parallel-work',
    title: 'Developers and runs working on bookshelf at the same time',
    projects: ['bookshelf-api'],
    real: false,
    scripted: true,
    covers: ['run.developer-work', 'guard.conflict', 'guard.land', 'project.main-line', 'feed.send-back', 'orchestrator.restart-recovery'],
    steps: [
      "A run lands in a file the developer is editing: their uncommitted change survives and their commit keeps the run's",
      'A developer and a chat change different parts of one file: both changes stand, no conflict',
      'Both change the same line: the conflict is raised over the file and resolved by a send back',
      'On a feature branch, runs land on the main line, also after a restart; merging the branch is indexed',
    ],
  },
  {
    id: 'sprint',
    title: 'A two-week sprint on todo-cli',
    projects: ['todo-cli'],
    real: false,
    scripted: true,
    covers: [
      'feed.rank', 'feed.send-back', 'feed.retire', 'orchestrator.serial-automations', 'orchestrator.parallel-user-runs', 'run.retry', 'run.failure',
      'metrics.attention', 'metrics.per-automation', 'app.timeline',
    ],
    steps: [
      'Sprint planning in the chat writes the sprint and its tasks, ranked by impact',
      'A task too big is sent back, split in two and retired',
      'Approved tasks are implemented one at a time in order, while the user chats',
      'A failed implementation leaves its task to do; started again on demand, it lands',
      'The sprint review: metrics and the timeline show the sprint',
    ],
  },
  {
    id: 'handbook-yearly-update',
    title: "The handbook's yearly update",
    projects: ['handbook'],
    real: false,
    scripted: true,
    covers: ['state.new-files', 'state.moved-files', 'automation.summarization', 'settings.persist', 'feed.retire', 'feed.approve'],
    steps: [
      'A new policy document is summarized into a new policy',
      'One commit across three documents is summarized in one run',
      'Policies moved into a folder: the cards follow their documents, their words unchanged',
      'A policy archived: its entity is proposed for retirement and kept while others reference it',
    ],
  },
  {
    id: 'morning-triage',
    title: 'A morning with a full feed from two projects',
    projects: ['handbook', 'todo-cli'],
    real: false,
    scripted: true,
    covers: ['feed.size', 'feed.rank', 'orchestrator.feed-room', 'feed.stale', 'metrics.attention', 'automation.graph-build', 'feed.issue-options', 'feed.wont-resolve'],
    steps: [
      'Overnight, automations in both projects fill the feed to its size and the build waits',
      'A quick triage: resolve, dismiss and approve, each timed',
      'A card that changed after the phone showed it is not approved unseen; its new version is',
      'With room made, the paused build goes on until complete',
    ],
  },
  {
    id: 'pull-requests',
    title: 'Pull requests merged into bookshelf day by day',
    projects: ['bookshelf-api'],
    real: false,
    scripted: true,
    covers: ['state.merges', 'state.new-files', 'state.artifact-ahead', 'automation.summarization', 'settings.persist', 'guard.main-line-index', 'feed.approve'],
    steps: [
      'A merged pull request with code, tests and a new module: one summarization run rewrites the cards it touches and maps the new files',
      'Two pull requests merged one after the other: summarized one at a time, the card ending on the latest',
      'A pull request with an excluded lockfile and a test: only the test is summarized',
      'A pull request reverted: the card follows the revert, the later change stays',
    ],
  },
  {
    id: 'review-rounds',
    title: 'A card through three review rounds',
    projects: ['todo-cli'],
    real: false,
    scripted: true,
    covers: ['feed.diff', 'feed.send-back', 'feed.approve', 'metrics.attention', 'app.timeline'],
    steps: [
      'A chat changes a card; it waits in the feed as a diff against the approved version',
      'Three rounds of send back: each diff is against the approved version, not the round before',
      'Approved: the diff goes, three send backs and one approval are counted, each comment is on the timeline',
      'The next change diffs against the card approved last',
    ],
  },
  {
    id: 'new-teammate',
    title: 'A new teammate finds their way around the handbook',
    projects: ['handbook'],
    real: false,
    scripted: true,
    covers: ['kb.search', 'app.pages', 'run.context', 'run.messages', 'automation.chat', 'feed.send-back', 'api.http'],
    steps: [
      'Searching the explorer finds the policy by its words and by its meaning; its card and document open',
      'A question with the policy as context is answered, and the follow-up keeps it',
      'A question the handbook does not answer becomes a FAQ that People Ops answers through a send back',
      'The next week the answer is found by search',
    ],
  },
  {
    id: 'busy-chat-day',
    title: 'A busy day of chats within the total of runs',
    projects: ['bookshelf-api'],
    real: false,
    scripted: true,
    covers: ['run.queue', 'orchestrator.concurrent-total', 'orchestrator.parallel-user-runs', 'run.messages', 'feed.once', 'run.kill'],
    steps: [
      'Five questions at once: three run, two wait, oldest first',
      'A follow-up to a waiting chat joins its first question and is answered with it',
      'A send back of the entity a chat is working on joins that chat',
      'A waiting chat stopped by the user never starts',
    ],
  },
];
